### ISSUE TITLE
Off by 1 error in jenks.pyx

### ISSUE THREAD

**Issue by mlsharp** [perrygeo/jenks#10]
Line 97 should be k = data.shape[0] instead of k = data.shape[0] - 1 (remove the -1).

Simple test: clustering this data set [1, 2, 3, 100] currently yields [1, 2, 100] but should yield [1, 3, 100]. Basically the large outlier 100 should be isolated into its own cluster.

**Comment by perrygeo** [comment]
Thanks @mlsharp , fixed in #11
